name: CI java test

on: workflow_dispatch

jobs:

  java-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: run test
        run: ./gradlew test