name: CI java test

on: workflow_dispatch

jobs:

  java-test:
    runs-on: ubuntu-latest

    steps:
      - name: print path
        run: |
          pwd
          ls -lh

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: test-branch

      - name: print path 2
        run: |
          pwd
          ls -lh

      - name: run test
        run: ./gradlew test