name: CI java test

on: workflow_dispatch

jobs:

  java-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print path
        run: ls | pwd

      - name: clone repository
        run: git clone https://github.com/shawnwu-linkage/GithubActions.git
