name: CI java test

on:
  push:
    branches:
      - main

jobs:

  java-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: test-branch

      - name: run test
        run: ./gradlew test